### ISSUE TITLE
Can't compile on RHEL 4.8, PHP 5.1.6

### ISSUE THREAD

**Issue by aubx** [iliaal/php_excel#26]
Hi,

I tried to compile extension on RHEL 4.8, PHP 5.1.6, but I'm getting error while compiling:

```
[user@dev1 excel-0.9.6]$ make
/bin/sh /home/user/excel-0.9.6/libtool --mode=compile gcc  -I. -I/home/user/excel-0.9.6 -DPHP_ATOM_INC -I/home/user/excel-0.9.6/include -I/home/user/excel-0.9.6/main -I/home/user/excel-0.9.6 -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/home/user/libxl-3.2.3/include  -DHAVE_CONFIG_H  -g -O2   -c /home/user/excel-0.9.6/excel.c -o excel.lo
 gcc -I. -I/home/user/excel-0.9.6 -DPHP_ATOM_INC -I/home/user/excel-0.9.6/include -I/home/user/excel-0.9.6/main -I/home/user/excel-0.9.6 -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/home/user/libxl-3.2.3/include -DHAVE_CONFIG_H -g -O2 -c /home/user/excel-0.9.6/excel.c  -fPIC -DPIC -o .libs/excel.o
/home/user/excel-0.9.6/excel.c:72: warning: parameter names (without types) in function declaration
/home/user/excel-0.9.6/excel.c: In function `PHP_GINIT_FUNCTION':
/home/user/excel-0.9.6/excel.c:5157: error: invalid type argument of `unary *'
/home/user/excel-0.9.6/excel.c:5157: error: incompatible type for argument 1 of `memset'
/home/user/excel-0.9.6/excel.c: At top level:
/home/user/excel-0.9.6/excel.c:5180: error: `excel' undeclared here (not in a function)
/home/user/excel-0.9.6/excel.c:5180: error: initializer element is not constant
/home/user/excel-0.9.6/excel.c:5180: error: (near initialization for `excel_module_entry.post_deactivate_func')
/home/user/excel-0.9.6/excel.c:5181: error: initializer element is not constant
/home/user/excel-0.9.6/excel.c:5181: error: (near initialization for `excel_module_entry.globals_id')
/home/user/excel-0.9.6/excel.c:5182: warning: initialization makes integer from pointer without a cast
/home/user/excel-0.9.6/excel.c:5183: warning: initialization makes integer from pointer without a cast
/home/user/excel-0.9.6/excel.c:5184: warning: excess elements in struct initializer
/home/user/excel-0.9.6/excel.c:5184: warning: (near initialization for `excel_module_entry')
/home/user/excel-0.9.6/excel.c:5184: warning: excess elements in struct initializer
/home/user/excel-0.9.6/excel.c:5184: warning: (near initialization for `excel_module_entry')
/home/user/excel-0.9.6/excel.c:5185: warning: excess elements in struct initializer
/home/user/excel-0.9.6/excel.c:5185: warning: (near initialization for `excel_module_entry')
make: *** [excel.lo] Greška 1
```
