### ISSUE TITLE
Library interface changed in LibXL v.3.5.4?

### ISSUE THREAD

**Issue by touringhaggis** [iliaal/php_excel#54]
I have tried to compile the head and v0.9.8 revisions against the latest version of LibXL (currently v.3.5.4.1) and in both cases I am getting errors from the compiler that indicate that the interface of the library has changed. I have tried to mess with the code to get it to compile (with apparent success), but 20% of the unit tests fail (for related or unrelated reasons). I am a little out of my depth so I will just report this and hope that someone more knowledgeable can fix this ;)

My PHP version is 3.4.16 and I am working on a Debian 6.0.8 box, although I doubt that is significant.

Here are the errors I am getting (significant ones at the end):
/usr/src/php_excel/excel.c:57: error: redeclaration of enumerator 'PICTURETYPE_PNG'
/usr/local/lib/libxl-3.5.4.1/include/enum.h:69: note: previous definition of 'PICTURETYPE_PNG' was here
/usr/src/php_excel/excel.c:57: error: redeclaration of enumerator 'PICTURETYPE_JPEG'
/usr/local/lib/libxl-3.5.4.1/include/enum.h:69: note: previous definition of 'PICTURETYPE_JPEG' was here
/usr/src/php_excel/excel.c:57: error: redeclaration of enumerator 'PICTURETYPE_WMF'
/usr/local/lib/libxl-3.5.4.1/include/enum.h:69: note: previous definition of 'PICTURETYPE_WMF' was here
/usr/src/php_excel/excel.c:57: error: redeclaration of enumerator 'PICTURETYPE_DIB'
/usr/local/lib/libxl-3.5.4.1/include/enum.h:69: note: previous definition of 'PICTURETYPE_DIB' was here
/usr/src/php_excel/excel.c:57: error: redeclaration of enumerator 'PICTURETYPE_EMF'
/usr/local/lib/libxl-3.5.4.1/include/enum.h:69: note: previous definition of 'PICTURETYPE_EMF' was here
/usr/src/php_excel/excel.c:57: error: redeclaration of enumerator 'PICTURETYPE_PICT'
/usr/local/lib/libxl-3.5.4.1/include/enum.h:70: note: previous definition of 'PICTURETYPE_PICT' was here
/usr/src/php_excel/excel.c:57: error: redeclaration of enumerator 'PICTURETYPE_TIFF'
/usr/local/lib/libxl-3.5.4.1/include/enum.h:70: note: previous definition of 'PICTURETYPE_TIFF' was here
/usr/src/php_excel/excel.c:57: error: redeclaration of enumerator 'PICTURETYPE_ERROR'
/usr/local/lib/libxl-3.5.4.1/include/enum.h:70: note: previous definition of 'PICTURETYPE_ERROR' was here
/usr/src/php_excel/excel.c: In function 'zim_ExcelSheet_setNamedRange':
/usr/src/php_excel/excel.c:3397: error: too few arguments to function 'xlSheetSetNamedRangeA'
/usr/src/php_excel/excel.c: In function 'zim_ExcelSheet_delNamedRange':
/usr/src/php_excel/excel.c:3421: error: too few arguments to function 'xlSheetDelNamedRangeA'
/usr/src/php_excel/excel.c: In function 'zim_ExcelSheet_getNamedRange':
/usr/src/php_excel/excel.c:3586: error: too few arguments to function 'xlSheetGetNamedRangeA'
/usr/src/php_excel/excel.c: In function 'zim_ExcelSheet_getIndexRange':
/usr/src/php_excel/excel.c:3611: error: too few arguments to function 'xlSheetNamedRangeA'

Regards,
Eric Ritchie.
