### ISSUE TITLE
php_excel 1.0.1 fails to build with libxl 3.6.3

### ISSUE THREAD

**Issue by ryandesign** [iliaal/php_excel#136]
Hello, I'm the maintainer of libxl and php_excel in MacPorts. libxl 3.6.3 has been released, but php_excel 1.0.1 fails to build with it. The error is:

```
/opt/local/var/macports/build/_Users_rschmidt_macports_dports_php_php-excel/php56-excel/work/php_excel-1.0.1final/excel.c:2872:71: error: too few arguments to function call, expected 8, have 7
 xlSheetSetPictureA(sheet, row, col, pic_id, scale, x_offset, y_offset);
 ~~~~~~~~~~~~~~~~~~                                                   ^
/opt/local/include/libxl-c/SheetA.h:64:21: note: 'xlSheetSetPictureA' declared here
                    void xlSheetSetPictureA(SheetHandle handle, int row, int col, int pictureId, double scale, int offset_x, int offset_y, int pos);
                    ^
/opt/local/var/macports/build/_Users_rschmidt_macports_dports_php_php-excel/php56-excel/work/php_excel-1.0.1final/excel.c:2891:71: error: too few arguments to function call, expected 9, have 8
 xlSheetSetPicture2A(sheet, row, col, pic_id, w, h, x_offset, y_offset);
 ~~~~~~~~~~~~~~~~~~~                                                  ^
/opt/local/include/libxl-c/SheetA.h:65:21: note: 'xlSheetSetPicture2A' declared here
                    void xlSheetSetPicture2A(SheetHandle handle, int row, int col, int pictureId, int width, int height, int offset_x, int offset_y, int pos);
                    ^
```

It builds fine with libxl 3.6.2.

**Comment by iliaal** [comment]
Fixed with latest git commit
