### ISSUE TITLE
libxl 4.0.0 linux php_excel php8 fails to compile

### ISSUE THREAD

**Issue by ericallenhoffman** [iliaal/php_excel#277]
I'm trying to compile the php8 branch against libxl 4.0.0 on debian linux. The build fails with the following errors:

`/usr/local/php_excel-php8/excel.c:6393:2: note: in expansion of macro 'REGISTER_EXCEL_CLASS_CONST_LONG'
  REGISTER_EXCEL_CLASS_CONST_LONG(book, "SHEETTYPE_SHEET", SHEETTYPE_SHEET);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/php_excel-php8/excel.c:261:106: error: expected ')' before 'TSRMLS_CC'
  zend_declare_class_constant_long(excel_ce_ ## class_name, const_name, sizeof(const_name)-1, (long)value TSRMLS_CC);
                                                                                                          ^~~~~~~~~
/usr/local/php_excel-php8/excel.c:6394:2: note: in expansion of macro 'REGISTER_EXCEL_CLASS_CONST_LONG'
  REGISTER_EXCEL_CLASS_CONST_LONG(book, "SHEETTYPE_CHART", SHEETTYPE_CHART);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/php_excel-php8/excel.c:261:106: error: expected ')' before 'TSRMLS_CC'
  zend_declare_class_constant_long(excel_ce_ ## class_name, const_name, sizeof(const_name)-1, (long)value TSRMLS_CC);
                                                                                                          ^~~~~~~~~
/usr/local/php_excel-php8/excel.c:6395:2: note: in expansion of macro 'REGISTER_EXCEL_CLASS_CONST_LONG'
  REGISTER_EXCEL_CLASS_CONST_LONG(book, "SHEETTYPE_UNKNOWN", SHEETTYPE_UNKNOWN);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/php_excel-php8/excel.c:261:106: error: expected ')' before 'TSRMLS_CC'
  zend_declare_class_constant_long(excel_ce_ ## class_name, const_name, sizeof(const_name)-1, (long)value TSRMLS_CC);
                                                                                                          ^~~~~~~~~
/usr/local/php_excel-php8/excel.c:6398:2: note: in expansion of macro 'REGISTER_EXCEL_CLASS_CONST_LONG'
  REGISTER_EXCEL_CLASS_CONST_LONG(book, "POSITION_MOVE_AND_SIZE", POSITION_MOVE_AND_SIZE);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/php_excel-php8/excel.c:261:106: error: expected ')' before 'TSRMLS_CC'
  zend_declare_class_constant_long(excel_ce_ ## class_name, const_name, sizeof(const_name)-1, (long)value TSRMLS_CC);
                                                                                                          ^~~~~~~~~
/usr/local/php_excel-php8/excel.c:6399:2: note: in expansion of macro 'REGISTER_EXCEL_CLASS_CONST_LONG'
  REGISTER_EXCEL_CLASS_CONST_LONG(book, "POSITION_ONLY_MOVE", POSITION_ONLY_MOVE);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/php_excel-php8/excel.c:261:106: error: expected ')' before 'TSRMLS_CC'
  zend_declare_class_constant_long(excel_ce_ ## class_name, const_name, sizeof(const_name)-1, (long)value TSRMLS_CC);
                                                                                                          ^~~~~~~~~
/usr/local/php_excel-php8/excel.c:6400:2: note: in expansion of macro 'REGISTER_EXCEL_CLASS_CONST_LONG'
  REGISTER_EXCEL_CLASS_CONST_LONG(book, "POSITION_ABSOLUTE", POSITION_ABSOLUTE);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:202: excel.lo] Error 1`

Any plans on making this module compatible with php 8.1?

**Comment by do-io** [comment]
The latest binaries available from libxl are working with php8.1. We also have this working with the Apple M1 chip
